### ISSUE TITLE
CSP Spot Check (database, jwt, login)

### ISSUE THREAD

**Issue by jm1021** [nighthawkcoders/teacher_portfolio#105]

**Comment by iKAN2025** [comment]
- [ ] Name Isabel Marilla
- [] Period 2
- [ ] Sum of Score
- [ ] [Link to Issue](https://github.com/iKAN2025/Nighthawk-Pages/issues/2)

**Comment by IshanCornick** [comment]
Name: Ishan Cornick
Period: 2
All scores:
Sum of best two scores: 
[Link to issue](https://github.com/iKAN2025/Nighthawk-Pages/issues/3)
 

**TO BE EDITTED**

**Comment by Tanuj253** [comment]
Name: Tanujsai Nimmagadda
Period 2
sum of score:
[link to Issue](https://github.com/Tanuj253/student2.0/issues/1)

**Comment by nitinsandiego** [comment]
Name: Nitin Balaji
Period 2
Sum of score: 0.9 + 0.9 = 1.80/2.00
[https://nitinsandiego.github.io/student//2024/01/31/Quiz-Review-Ticket.html](link to issue)

**Comment by hanlunli** [comment]
- [ ] Hanlun Li
- [ ] Period 2
- [ ] 2.0/2.0
- [ ] [link to issue](https://github.com/hanlunli/student/issues/4)

**Comment by DavidL0914** [comment]
David Lee, Period 2
Score Sum: 0.9 + 0.7 = 1.6
[Link to Issue](https://github.com/DavidL0914/student/issues/8#issue-2110829442)

Question 1:
0.7
Comments: Use SQLite3 DB to show new column (utilize extensions)

Question 2:
0.9
Comments: Good!

Question 3:
N/A

**Comment by M8tth3** [comment]
[ ] Matthew Wakayama
[ ] Period 2 
[ ] Sum of Score(2.0)
[ ] [Link To Issue](https://github.com/M8tth3/m8th3_2.0/issues/2)

**Comment by ad1tyad3sa1** [comment]
> * [ ]  Aditya Desai
> * [ ]  Period 2
> * [ ]  Sum of Score (2.7/3)
> * [ ]  [Link to Issue](https://github.com/ad1tyad3sa1/adityadesai2.0/issues/1)

**Comment by jplip** [comment]
Justin Liporada
Period 2
 Sum of Score 2.0/2.0
[ Link to Issue](https://github.com/jplip/justin2.0/issues/2)

**Comment by trevorhuang1** [comment]
Trevor Huang
Period 2
Sum of score: 0.9 + 0.9 +0.9 = 2.7/3.0
<a href="https://github.com/trevorhuang1/csp_blog/issues/3">Link to issues</a>

**Comment by vibha-yganji** [comment]
- [ ] Vibha Ganji
- [ ] Period 2
- [ ] Sum of Score
- [ ] [Link to Issue](https://github.com/vibha-yganji/student-vibha/issues/1)

**Comment by Th35py27** [comment]
Name: Nandan Vallamkondu
Period 2
sum of score:
Link to issue: https://github.com/Th35py27/CSP/issues/2

To be edited soon

**Comment by 7mwang** [comment]
Name: Matthew Wang
Period 2
Sum of scores: 0+0.9+0.9=1.8
Link to issue:

**Comment by KinetekEnergy** [comment]
Name: Aashray Reddy
Period: P5
Sum of Score: 1.83
Link to Issue: https://github.com/KinetekEnergy/blog/issues/1

**Comment by spooketti** [comment]
Name: Jonathan Liu
Period 5
Sum of Scores: 0.92 +.91 +.91=
.91/1 (best of 2 scores)
link to issue <a href="https://github.com/spooketti/studentmodern/issues/6">Issue</a>

**Comment by SrijDude3416** [comment]
Name: Srijan Atti
Period 5
Scores: 0.92, 0.9, 0.91
Final score: 2.0
[Link to issue](https://github.com/SrijDude3416/student-backend/issues/1)

**Comment by varunm532** [comment]
Name Varun Manoj Pillai
Per 2
link to issue: https://github.com/varunm532/varun2/issues/10
question 1 not graded yet 
question 2: 0.9
question 3: 0.7

**Comment by Flying-Book** [comment]
Name: Anusha Khobare
Per: 2
Sum of Scores (best 2): 1.8/2
[Link to Issue](https://github.com/Flying-Book/CSP_home/issues/1#issue-2111581977)

**Comment by RayyanDarugar** [comment]
Name: Rayyan Darugar
Per: 5
Sum of Scores (Top 2): 1.83
[Link to Issue](https://github.com/RayyanDarugar/student/issues/5#issue-2111184582)

**Comment by AnvayYadav** [comment]
Name: Anvay Yadav
Per: 1
In Progress, Not had spot chock yet

**Comment by hanlunli** [comment]
Name: Hanlun Li
Period 2
Sum of Scores (best 2): 1.8 (or 2.0 since I got 0.9 for all 3)
[link](https://github.com/hanlunli/student/issues/4)

**Comment by LincolnC2008** [comment]
Name: Lincoln Crowell
Period: 2
Sum of Scores: to be determined.
Link to issue: https://github.com/LincolnC2008/student3/issues/2

**Comment by lakshusan** [comment]
Name: Lakshanya Sankaran
Period 2
Sum of score: 0.9 + 0.9 = 1.80/2

(all 3 q's complete with 0.9)
[link to issue](https://github.com/lakshusan/student2/issues/3)

**Comment by Lin-cT** [comment]
Name: Lindsay Tang
Period: 5
Sum of Scores: Not graded yet
[Link to Issue](https://github.com/Lin-cT/demonstration_backend/issues/1)

**Comment by sharonkodali** [comment]
Name: Sharon Kodali
Period: 2
Sum or scores: 0.9+0.9=1.80/2 ( I got 0.9 for all 3 questions)
[Link to issues :](https://github.com/sharonkodali/sharonk/issues)

**Comment by alaraipek** [comment]
Name: Alara Ipek
Period: 2
Sum of Scores: Not graded yet
[Link to Issue](https://github.com/alaraipek/Issues/issues/10)

**Comment by tuckergol** [comment]
Name: Tucker Golpariani
Period 2
Sum of Scores: 0.9 + 0.9 = **1.8/2** (top two scores)
[Link to issue](https://github.com/tuckergol/student2/issues/12)

**Comment by SGTech08** [comment]
Name: Saathvik Gampa
Period 2
Sum of Scores: 0.9+0.9 = 1.8/2 (top 2 scores)
[Line to Issue](https://github.com/SGTech08/student/issues/13)

**Comment by Imaad08** [comment]
Name: Imaad Muzaffer
Period 1
Current Score: 1.83/2
[Issue](https://github.com/Imaad08/student2/issues/7)

**Comment by DrishyaMody** [comment]
Drishya Mody 
Mr. Lopez Period 4
Sum of scores: 1.81/2
link to issue : https://github.com/DrishyaMody/student2/issues/3

**Comment by Imaad08** [comment]
Name: Imaad Muzaffer
Period 1
Current Score: 1.83/2
[Link to Issue](https://github.com/Imaad08/student2/issues/7)

**Comment by jaydenchen17** [comment]
Jayden Chen
Mr. Lopez p1
Sum of Scores: 0.91+0.91= 1.82
[link to issue](https://github.com/jaydenchen17/jcflask/issues/1)

**Comment by peytonl11098** [comment]
Name: Peyton Leigh
Period: 2
Sum or scores:  
[Link to issues :](https://github.com/peytonl11098/Ultron/issues)

**Comment by TDWolff** [comment]
Name: Torin Wolff
Period: 2
Sum: 1.9/2 (95%)
Link To Issue: [Link](https://github.com/TDWolff/AtlasIndex/issues/3)

**Comment by alishahussain** [comment]
Name: Alisha Hussain
Period: 2
Sum of Scores: 0.9+0.9 = 1.8
[Link to Issue](https://github.com/sharonkodali/CPTproject/issues/4)

**Comment by tarasehdave** [comment]
Name: Tara Sehdave 
Period: 2
Sum of Scores: 0.9 + 0.0 = 0.45 
[Link to Issue](https://github.com/tarasehdave/tarasehdave.github.io/issues/1)

**Comment by sergi1207** [comment]
Name: Sergi S. 
Period 2
Final Score: 1.6/2
[Link to issue](https://github.com/jm1021/sergiStudent/issues/1)

**Comment by KaydenLe** [comment]
Name: Kayden Le
Period 2
Sum of scores:
[Link to issue Q1:](https://github.com/KaydenLe/kaydentri2/issues/1)
[Link to issue Q2:](https://github.com/KaydenLe/kaydentri2/issues/2)
[Link to issue Q3:](https://github.com/KaydenLe/kaydentri2/issues/3)

**Comment by MEERIE** [comment]
NAME - AMEER
PERIOD 2
FINAL SCORE: 
[LINK TO QUESTION 3](https://github.com/MEERIE/stew2/issues/2)
[LINK TO QUESTION 2](https://github.com/MEERIE/stew2/issues/1)

**Comment by ak146** [comment]
Andrew K
P:2
Sum or scores:
[Issue](https://github.com/ak146/FunnyBlog2.0/issues/4)

**Comment by anikabhatnagar20** [comment]
Anika Bhatnagar 
Period: 2
Sum of Scores: .9+ 
[Issue](https://github.com/anikabhatnagar20/anikabhatnagar20/issues/3#issue-2110775510)

**Comment by brandonso36** [comment]
Name: Brandon So
Period 1
Sum of Scores: 0.92 + 0.91 = 1.83/2 (top two scores)
[Link to Issue](https://github.com/brandonso36/brandonso/issues/7)

**Comment by AkshayNagesh** [comment]
Name: Akshay Nagesh
Period: 2
Sum of Scores: Not Graded Yet
[Link To Issue](https://github.com/AkshayNagesh/_posts/issues/1#issue-2112971458)

**Comment by advikg** [comment]
Name: Advik Garg
Period: 5
Sum of Scores: All 3 above .90, 2.00/2.00
[Link to Issue](https://github.com/advikg/login-csp-backend/issues/1#issue-2111170391)

**Comment by Nathaniel633** [comment]
Name: Nathaniel Obodovski
Per: 5
Sum of Scores 0.91 x 3 
https://github.com/Nathaniel633/student/issues/10

**Comment by tarunja1ks** [comment]
Name: Tarun Jaikumar
Period: 5
Sum of Scores: 0.91+0.90= **1.81/2** (Top 2 scores)
[Issue ](https://github.com/tarunja1ks/student/issues/1)

**Comment by iwu78** [comment]
Name: Ian Wu
Period: 5
Sum of Scores: 0.92 + 0.93 = 1.85/2, 3 scores above 0.9 so 2/2
[Link to Issue](https://github.com/iwu78/csp-blog/issues/7)

**Comment by AidanLau10** [comment]
Name: AIdan Lau
Period: 1
Sum of Scores: 0.91 + 0.90 + 0.91 = 2/2
[Issue](https://github.com/AidanLau10/student2/issues/26)

**Comment by JasonGao76** [comment]
Name: Jason Gao
Period: 5
Sum of Score: 2/2 (0.92 for Q1, 0.91 for Q2, and 0.91 for Q3, so 3 scores above 0.9 qualifies for 2/2)
[Link to Issue](https://github.com/JasonGao76/students/issues/6)

**Comment by VanceReynolds** [comment]
Vance Reynolds
Period 2
Sum of Score: 
[Link to Issue](https://github.com/VanceReynolds/cspblog2/issues/5)

**Comment by Ishraqh1** [comment]
Ishraq Hossain
Period 4, Lopez
Second Score: 0.89 Third Score 0.9 First Score: 0.55 (Didn't get to finishing it)
Total Score: 1.79/2

**Comment by ninaadkiran** [comment]
> * [x]  Ninaad Kiran
> * [x]  Period 4
> * [x]  0.91+0.90 = 1.81
> * [x]  [Link to issue](https://github.com/ninaadkiran/Ninaad-Repository2/issues/3)

**Comment by samhita-l** [comment]
Samhita Lagisetti
Period 5, Lopez
First Score: 0.91, Second Score: 0.9, Third Score: 0.9
All 3 are 0.9 or above, so 2/2

**Comment by monke7769** [comment]
Hayden Chen
P5 Lopez
First score: 0.9, second score: 0.9, third score: 0.9
2/2

**Comment by srivaidyas** [comment]
Sri Vaidyanathan S
P4 Lopez
Q1: 0.89, Q2: 0.89, Q3: 0.90
Sum of scores: 0.89+0.90=1.79/2.0
[Link to issue](https://github.com/srivaidyas/student2.0/issues/36)

**Comment by Djxnxnx** [comment]
Tarun Tata
P1 Lopez
First Score: 0.89, Second Score: 0.89, Third Score: 0.88
0.89 + 0.89 = 1.78/2
[Link to issue](https://github.com/Djxnxnx/student/issues/6)

**Comment by abdullahkhanani9** [comment]
Abdullah Khanani
P2 Mortensen
First Score: 0.9, Second Score: 0, Third Score: 0.9
0.9+0.9=1.8/2
[Link to Issue](https://github.com/abdullahkhanani9/abdullahrepository2/issues/1#issue-2116669385)

**Comment by nikkihekmat** [comment]
Nikki Hekmat
Period 4 Lopez
Sum of Scores: 0.91 + 0.92 = 1.83/2.00
[Link to Issue](https://github.com/nikkihekmat/student-2.0/issues/1)

**Comment by AdityaSamavedam** [comment]
Aditya Samavedam
Period 5, Lopez
First Score: 0.90
Second Score: 0.91
Third Score: 0.88
Total Score: 1.81/2
[Link To Issue](https://github.com/AdityaSamavedam/cptbackend/issues/1#issue-2117344069)

**Comment by daniel-s-lee** [comment]
Daniel Lee
P4 Lopez
Sum of scores: .88 + .86 = .1.74/2
[https://github.com/daniel-s-lee/dslee/issues/3](url)

**Comment by willbartelt15** [comment]
Will Bartelt
P5 Lopez
Sum of scores .9+.9=1.8
[Link to issue](https://github.com/willbartelt15/stu4/issues/1)

**Comment by saiseahawks** [comment]
Sai Talisetty
P5 Lopez
Sum of top scores: .90 + .90 = 1.80
Link to Issue[https://github.com/saiseahawks/cptBackEnd/issues/1](url)

**Comment by eunseolim123** [comment]
Eunseo Lim
P4 Lopez
Sum of scores: 0.91 + 0.90 = 1.81/2
[Link to issue](https://github.com/eunseolim123/student-2.0/issues/1)

**Comment by BearytheGreenBear** [comment]
Kyle Liang
P1 Lopez
Sum of Scores: .91, .90, .89, (.91+.90) / 2 = **1.81 / 2**
[Link to Issue](https://github.com/BearytheGreenBear/csp-blog/issues/4)

**Comment by RonitT1234** [comment]
Ronit Thomas
Period 1 Mr.Lopez 
Score: 1.83/2
![link](https://github.com/RonitT1234/CSP_BLOG_RT/issues/11)

**Comment by Akhil353** [comment]
Akhil Singamneni
Period 1 Mr. Lopez
Score: 1.8/2
[Issue](https://github.com/Akhil353/flask-2/issues/1)

**Comment by will-w-cheng** [comment]
William Cheng
Period 5 Mr. Lopez
Score: (2/2)
[Link](https://github.com/will-w-cheng/backend-quiz/issues/1)

**Comment by Arushi-maker** [comment]
Arushi Pandey
Period 4, Lopez
Second Score: 0.89 Third Score 0.90 First Score: 0.55 (Didn't have time in class to complete it)
Total Score: 1.79/2.0
[Link to Issue](https://github.com/Arushi-maker/students/issues/5)

**Comment by HowieNguyen21** [comment]
Howie Nguyen
Period 4, Lopez
First: 0.86 Second: 0.89 Third: 0.88
Total Score: 1.77/2.0
[Link to issue](url)

**Comment by KaiyuSugiyama** [comment]
Kaiyu Sugiyama
Period 4
Sum of score: 0+0.9+0.9=1.80/2 
[Link to Issue](https://github.com/KaiyuSugiyama/studentactual/issues/1)

**Comment by JBaza12** [comment]
Jared Baza
Period 4 Lopez
Score: 1.78/2
[Issue](https://github.com/JBaza12/JaredsBlog/issues/1)

**Comment by wl0503** [comment]
William Lee
Period 4, Lopez
Score: 1.79/2
[Link to issue](https://github.com/wl0503/wl0503/issues/2)

**Comment by AidanDelgado2** [comment]
Aidan Delgado
Period 4 Lopez
Score: .89+.9=1.79/2
[Issue](https://github.com/AidanDelgado2/Student2Backend/issues/1)

**Comment by Ankit-177** [comment]
Ankit Pulivendula
Period 4 with Mr. Lopez
Sum of best scores: (0.89+0.90) = **1.79/2**
[Link to issue](https://github.com/Ankit-177/ankit_tri2/issues/1)

**Comment by tanav-kambhampati** [comment]
Tanav Kambhampati
Period 1 Lopez
Sum of best scores: (0.83+0.82) = 1.65/2

**Comment by YeongsuKimm** [comment]
Yeongsu Kim
Period 5 Lopez
Sum of best scores: (0.90 + 0.91) = 1.81/2

**Comment by SriS126** [comment]
Sri Surapaneni
Period 5 Lopez
Sum Of Scores: (0.90+0.90) = 1.8/2

**Comment by Nupurbb** [comment]
Nupur Bhalla
Period 5
score: Q2+Q3= 0.9+0.9= 1.80/2.0
issue: https://github.com/Nupurbb/student3/issues/1#issue-2119644447

**Comment by PatrickHastings2** [comment]
Patrick Hastings
Period 4
Question 1 .90 Question 2 .90 = 1.80

[Issue](https://github.com/PatrickHastings2/STUDENT2REPO/issues/1)

**Comment by dino596** [comment]
Arthur Liu
Period 4
Question 1: 0.89
Question 2: 0.55
Question 3: 0.87
Score: (0.89+0.87)/2 = 0.88

**Comment by beijanm** [comment]
Beijan Moniza
Period 4, Lopez
Score: 1.82/2
https://github.com/beijanm/beijan.web/issues/3

**Comment by Sreejarai123** [comment]
Sreeja Rai
Period 1, Lopez
Score: 1.82/2
link to issue: https://github.com/Sreejarai123/2nd-student/issues

**Comment by tanav-kambhampati** [comment]
Tanav Kambhampati
Period 1 Lopez
Score: 1.69
Link to Issue: https://github.com/tanav-kambhampati/student2/issues/4

**Comment by TejM123** [comment]
Tejas Manoj
Period 1, Lopez
Score: 1.8/2
link to issue: https://github.com/TejM123/student2/issues/1#issue-2117780524

**Comment by ellierozen** [comment]
Ellie Rozenkrants 
Period 4 Lopez 
Score: 1.8
Link to issue:

**Comment by sfremy** [comment]
Name: Remy Liu
Period 4
Sum of Scores: 0.9+0.9+0.89 = 2.69
[Link to Issue](https://github.com/sfremy/login_api_experiments/issues/1#issue-2121505750)

**Comment by tanvim-18** [comment]
Name: Tanvi Movva
Period 1
Score 1.8/2
Link to issue: https://github.com/tanvim-18/student/issues/2

**Comment by cliang1** [comment]
Name: Cindy Liang
Period 5
Score: 1.79/2.0
[Link to Issue](https://github.com/cliang1/cliang/issues/6#issue-2116001499)

**Comment by SrinivasNampalli** [comment]
Name: Srinivas Nampalli 
Period 5
Score: 1.73/2.0
Link to Issue: https://github.com/SrinivasNampalli/NewStudent/issues/6

**Comment by EthanH06** [comment]
Name: Ethan Hong
Period 4
Sum of Scores: 0.9 + 0.55(didn't do) + 0.87 = 1.77/2
Link : [https://github.com/EthanH06/EthanH3-Backend2/issues/1#issue-2123971172](url)

**Comment by devaSas1** [comment]
Name: Deva Sasikumar
Period 5
Sum of Scores: 0.88+0.89 = 1.77/2
Link: https://github.com/devaSas1/student/issues/3#issue-2126222095

**Comment by anaghaa1206** [comment]
Name: Anagha Ashtewale
Period 1
Sum of Scores 0.92+0.90 = 1.82/2
Link: [https://github.com/anaghaa1206/anagha12/issues/1](url)

**Comment by miggysp** [comment]
Name: Miheer Purandare
Period 1
Sum of Scores: 0.92 + 0.90 = 1.82/2
Link to Issue: [Issue](https://github.com/miggysp/student2/issues/1#issue-2152576917)

**Comment by AdiBricks** [comment]
Aditya Ramesh
Period 5
Sum of score: 0.9 + 0.89 +0.84 = 2.63/3.0
https://github.com/AdiBricks/StudentRepoProper/issues/1

**Comment by aashrayr** [comment]
Aashray Rajagopalan
Period 1
Sum: 0.9 + 0.9 + 0.9 = 2.7/3
https://github.com/aashrayr/student2/issues/3

**Comment by abby-albert** [comment]
Abby Albert 
Period 1
Score 1.8/2
https://github.com/abby-albert/s2/issues/1

**Comment by Chrissiez** [comment]
Chrissie Zhou
Period 1
Score 1.82/2
[link to issue](https://github.com/Chrissiez/students/issues/6)

**Comment by AustinZhang1** [comment]
Austin Zhang
Period 4
Score: 1.85/2
[Link to Issue](https://github.com/AustinZhang1/student/issues/2)

**Comment by KaramKambo** [comment]
Name: Karam Kambo
Period 4
Sum of Scores: 0.9+0.91+0.55 = 1.81 (two highest score)
https://github.com/KaramKambo/stunew/issues/2

**Comment by Saaras859** [comment]
Saaras Kodali
Period 4 
Score: 1.82/2
[https://github.com/Saaras859/student-public/issues/3](url)

**Comment by Aditi99b** [comment]
Aditi Bharadwaj 
Period 5
Score: 1.8/9
[blog post ](https://github.com/Aditi99b/login/issues/1)

**Comment by avanthikadaita** [comment]
Avanthika Daita
Period: 5
Score:
[Issue](https://github.com/avanthikadaita/student-10/issues/1)

**Comment by EshikaP1** [comment]
Eshika Pallapotu
Period 5:
[Issue](https://github.com/EshikaP1/Student2/issues/5)
